-- ==========================================
-- 🚀 Supabase Schema Migration: Mosabqah SaaS
-- ==========================================

-- 1. Enable UUID Extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. Create Profiles Table (User Account Info & Roles)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    username TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('admin', 'presenter')) DEFAULT 'presenter',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Profiles Policies
CREATE POLICY "Allow public read access to profiles" ON public.profiles
    FOR SELECT USING (true);

CREATE POLICY "Allow users to update their own profile" ON public.profiles
    FOR UPDATE USING (auth.uid() = id);

-- Trigger to automatically create profile on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, username, role)
    VALUES (
        new.id,
        COALESCE(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1)),
        COALESCE(new.raw_user_meta_data->>'role', 'presenter')
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- 3. Create Questions Table (Central Questions Bank)
CREATE TABLE IF NOT EXISTS public.questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_text TEXT NOT NULL,
    option1 TEXT NOT NULL,
    option2 TEXT NOT NULL,
    option3 TEXT DEFAULT '',
    option4 TEXT DEFAULT '',
    correct_option INTEGER NOT NULL CHECK (correct_option BETWEEN 1 AND 4),
    difficulty TEXT NOT NULL CHECK (difficulty IN ('easy', 'medium', 'hard')) DEFAULT 'medium',
    category TEXT NOT NULL DEFAULT 'general',
    image_url TEXT,
    created_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on questions
ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;

-- Questions Policies
CREATE POLICY "Allow authenticated users to read questions" ON public.questions
    FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Allow admins to modify questions" ON public.questions
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.profiles 
            WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
        )
    );


-- 4. Create Sessions Table (Game Rooms created by presenters)
CREATE TABLE IF NOT EXISTS public.sessions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    title TEXT NOT NULL,
    room_code TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL CHECK (status IN ('waiting', 'active', 'finished')) DEFAULT 'waiting',
    current_question_id BIGINT REFERENCES public.questions(id) ON DELETE SET NULL,
    question_status TEXT NOT NULL CHECK (question_status IN ('idle', 'showing', 'revealed', 'time_up')) DEFAULT 'idle',
    timer_duration INTEGER NOT NULL DEFAULT 30,
    show_scoreboard BOOLEAN NOT NULL DEFAULT false,
    created_by UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on sessions
ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;

-- Sessions Policies
CREATE POLICY "Allow public read access to sessions" ON public.sessions
    FOR SELECT USING (true);

CREATE POLICY "Allow presenters to manage their own sessions" ON public.sessions
    FOR ALL USING (auth.uid() = created_by);


-- 5. Create Session Questions Mapping Table (Many-to-many relationship)
CREATE TABLE IF NOT EXISTS public.session_questions (
    session_id UUID REFERENCES public.sessions(id) ON DELETE CASCADE,
    question_id BIGINT REFERENCES public.questions(id) ON DELETE CASCADE,
    PRIMARY KEY (session_id, question_id)
);

-- Enable RLS on session_questions
ALTER TABLE public.session_questions ENABLE ROW LEVEL SECURITY;

-- Session Questions Policies
CREATE POLICY "Allow public read access to session questions" ON public.session_questions
    FOR SELECT USING (true);

CREATE POLICY "Allow presenters to manage questions for their sessions" ON public.session_questions
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.sessions
            WHERE sessions.id = session_id AND sessions.created_by = auth.uid()
        )
    );


-- 6. Create Players Table (Public participants joined via room code)
CREATE TABLE IF NOT EXISTS public.players (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    session_id UUID REFERENCES public.sessions(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    color TEXT NOT NULL,
    score INTEGER NOT NULL DEFAULT 0,
    streak INTEGER NOT NULL DEFAULT 0,
    lifelines_remaining INTEGER NOT NULL DEFAULT 2,
    lifelines_time_remaining INTEGER NOT NULL DEFAULT 2,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(session_id, name)
);

-- Enable RLS on players
ALTER TABLE public.players ENABLE ROW LEVEL SECURITY;

-- Players Policies
CREATE POLICY "Allow public access to players table" ON public.players
    FOR ALL USING (true);


-- 7. Create Player Answers Table (Tracks contestant submissions)
CREATE TABLE IF NOT EXISTS public.player_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id UUID REFERENCES public.sessions(id) ON DELETE CASCADE,
    player_id UUID REFERENCES public.players(id) ON DELETE CASCADE,
    question_id BIGINT REFERENCES public.questions(id) ON DELETE CASCADE,
    chosen_option INTEGER NOT NULL CHECK (chosen_option BETWEEN 1 AND 4),
    is_correct BOOLEAN NOT NULL,
    time_spent NUMERIC NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(session_id, player_id, question_id)
);

-- Enable RLS on player_answers
ALTER TABLE public.player_answers ENABLE ROW LEVEL SECURITY;

-- Player Answers Policies
CREATE POLICY "Allow public access to insert answers" ON public.player_answers
    FOR ALL USING (true);


-- 8. Create Winners Archive Table (Permanent winners log)
CREATE TABLE IF NOT EXISTS public.winners_archive (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    session_id UUID REFERENCES public.sessions(id) ON DELETE SET NULL,
    session_title TEXT NOT NULL,
    winner_name TEXT NOT NULL,
    winner_score INTEGER NOT NULL,
    total_players INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on winners_archive
ALTER TABLE public.winners_archive ENABLE ROW LEVEL SECURITY;

-- Winners Archive Policies
CREATE POLICY "Allow public read access to winners archive" ON public.winners_archive
    FOR SELECT USING (true);

CREATE POLICY "Allow presenters to insert winners" ON public.winners_archive
    FOR INSERT WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.sessions
            WHERE sessions.id = session_id AND sessions.created_by = auth.uid()
        )
    );


-- 9. Create Cumulative Leaderboard Table (Long-term seasonal standings)
CREATE TABLE IF NOT EXISTS public.cumulative_leaderboard (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    player_name TEXT NOT NULL UNIQUE,
    total_score INTEGER NOT NULL DEFAULT 0,
    games_played INTEGER NOT NULL DEFAULT 1,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on cumulative_leaderboard
ALTER TABLE public.cumulative_leaderboard ENABLE ROW LEVEL SECURITY;

-- Cumulative Leaderboard Policies
CREATE POLICY "Allow public read access to cumulative leaderboard" ON public.cumulative_leaderboard
    FOR SELECT USING (true);

CREATE POLICY "Allow authenticated hosts to modify cumulative leaderboard" ON public.cumulative_leaderboard
    FOR ALL USING (auth.role() = 'authenticated');

-- 10. Database function to increment cumulative leaderboard
CREATE OR REPLACE FUNCTION public.increment_cumulative_score(p_name TEXT, p_score INTEGER)
RETURNS VOID AS $$
BEGIN
    INSERT INTO public.cumulative_leaderboard (player_name, total_score, games_played, updated_at)
    VALUES (p_name, p_score, 1, now())
    ON CONFLICT (player_name)
    DO UPDATE SET
        total_score = public.cumulative_leaderboard.total_score + EXCLUDED.total_score,
        games_played = public.cumulative_leaderboard.games_played + 1,
        updated_at = now();
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
